image: maven:3.3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s $MVN_SETTINGS --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

deploy:
  script:
    - mvn $MAVEN_CLI_OPTS deploy

  only:
    - master