image: maven:3.3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - mkdir .m2
  - cat $MVN_SETTINGS > .m2/settings.xml

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

deploy:
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
